project:
  title: "Отчёт по лабораторной работе № 6"
  output-dir: "_output"

lang: ru-RU
number-sections: true
toc: true
toc-title: "Содержание"
toc-depth: 2

format:
  docx:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
